<a href="https://colab.research.google.com/github/shyamprasadg22/FDS-Experiments/blob/main/ShyamprasadG_250701711_Exp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# Handling Missing and Inappropriate Data in a Dataset

import numpy as np
import pandas as pd

# Upload Hotel.csv and convert it into DataFrame
# Make sure to upload the 'Hotel_Dataset.csv' file to your Colab environment
# If uploaded, it will typically be found in the /content/ directory.
df = pd.read_csv('Hotel_Dataset.csv')

# Display the dataset
df

# Identify duplicate rows
df.duplicated()

# Display information about the DataFrame
df.info()

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Display the dataframe
df

# Find the number of rows
len(df)

# Reset the index
index = np.array(list(range(0, len(df))))
df.set_index(index, inplace=True)

# Display index
index

# Display dataframe
df

# Remove duplicate Age_Group column
df.drop(['Age_Group.1'], axis=1, inplace=True)

# Display dataframe
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       11 non-null     int64
 1   Age_Group        11 non-null     object
 2   Rating(1-5)      11 non-null     int64
 3   Hotel            11 non-null     object
 4   FoodPreference   11 non-null     object
 5   Bill             11 non-null     int64
 6   NoOfPax          11 non-null     int64
 7   EstimatedSalary  11 non-null     int64
 8   Age_Group.1      11 non-null     object
dtypes: int64(5), object(4)
memory usage: 924.0+ bytes

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000
2,3,25-30,6,RedFox,Veg,1322,2,30000
3,4,20-25,-1,LemonTree,Veg,1234,2,120000
4,5,35+,3,Ibis,Vegetarian,989,2,45000
5,6,35+,3,Ibys,Non-Veg,1909,2,122220
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122
7,8,20-25,7,LemonTree,Veg,2999,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777

In [ ]:
# Replace negative CustomerID values with NaN
df.loc[df.CustomerID < 0, 'CustomerID'] = np.nan

# Replace negative Bill values with NaN
df.loc[df.Bill < 0, 'Bill'] = np.nan

# Replace negative EstimatedSalary values with NaN
df.loc[df.EstimatedSalary < 0, 'EstimatedSalary'] = np.nan

# Replace invalid NoOfPax values
# NoOfPax should be between 1 and 20
df.loc[(df['NoOfPax'] < 1) | (df['NoOfPax'] > 20), 'NoOfPax'] = np.nan

# Display dataframe
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Vegetarian,989.0,2.0,45000.0
5,6.0,35+,3,Ibys,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Vegetarian,1000.0,NaN,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,NaN,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,NaN
9,10.0,30-35,5,RedFox,non-Veg,NaN,4.0,87777.0

In [ ]:
# Display unique Age_Group values
df.Age_Group.unique()

# Display unique Hotel values
df.Hotel.unique()

# Replace incorrect hotel name
df.Hotel.replace(['Ibys'], 'Ibis', inplace=True)

# Display unique food preferences
df.FoodPreference.unique()

# Convert different forms of Veg to one standard value
df.FoodPreference.replace(
    ['Vegetarian', 'veg'],
    'Veg',
    inplace=True
)

# Convert different forms of Non-Veg to one standard value
df.FoodPreference.replace(
    ['non-Veg'],
    'Non-Veg',
    inplace=True
)

# Display dataframe
df

/tmp/ipykernel_1398/2484419667.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Hotel.replace(['Ibys'], 'Ibis', inplace=True)
/tmp/ipykernel_1398/2484419667.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.FoodPreference.replace(

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,2.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,NaN,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,NaN,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,NaN
9,10.0,30-35,5,RedFox,Non-Veg,NaN,4.0,87777.0

In [ ]:
# Fill missing EstimatedSalary using mean
df.EstimatedSalary.fillna(
    round(df.EstimatedSalary.mean()),
    inplace=True
)

# Fill missing NoOfPax using median
df.NoOfPax.fillna(
    round(df.NoOfPax.median()),
    inplace=True
)

# Fill missing Rating using median
df['Rating(1-5)'].fillna(
    round(df['Rating(1-5)'].median()),
    inplace=True
)

# Fill missing Bill using mean
df.Bill.fillna(
    round(df.Bill.mean()),
    inplace=True
)

# Display final dataframe
df

/tmp/ipykernel_1398/1476369604.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.EstimatedSalary.fillna(
/tmp/ipykernel_1398/1476369604.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NoOfPax.fillna(
/tmp/ipykernel_1398/1476369604.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating(1-5)'].fillna(
/tmp/ipykernel_1398/1476369604.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Bill.fillna(

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4,Ibis,Veg,1300.0,2.0,40000.0
1,2.0,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3,Ibis,Veg,989.0,2.0,45000.0
5,6.0,35+,3,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4,RedFox,Veg,1000.0,2.0,21122.0
7,8.0,20-25,7,LemonTree,Veg,2999.0,2.0,345673.0
8,9.0,25-30,2,Ibis,Non-Veg,3456.0,3.0,96755.0
9,10.0,30-35,5,RedFox,Non-Veg,1801.0,4.0,87777.0